# Generated by Django 3.0.6 on 2020-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminEventRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='req',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='date',
            field=models.DateField(),
        ),
    ]
